import { Geist, Geist_Mono, Roboto } from "next/font/google";
import Script from "next/script";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Ecommerce Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
      >
        <Script
          src="https://unpkg.com/supersimpledev/chatbot.js"
          strategy="afterInteractive"
        />

        <div className="header">
          <div className="left-section">
            <a href="index.html" className="header-link">
              <Image
                className="logo"
                src="/images/logo-white.png"
                alt="Logo"
                width={177}
                height={26}
                priority
              />

              <Image
                className="mobile-logo"
                src="/images/mobile-logo-white.png"
                alt="Mobile Logo"
                width={22.53}
                height={36}
              />
            </a>
          </div>

          <div className="middle-section">
            <input className="search-bar" type="text" placeholder="Search" />

            <button className="search-button">
              <Image
                className="search-icon"
                src="/images/icons/search-icon.png"
                alt="Search"
                width={17.5}
                height={20}
              />
            </button>
          </div>

          <div className="right-section">
            <a className="orders-link header-link" href="orders.html">
              <span className="orders-text">Orders</span>
            </a>

            <a className="cart-link header-link" href="checkout.html">
              <Image
                className="cart-icon"
                src="/images/icons/cart-icon.png"
                alt="Cart"
                width={38}
                height={33}
              />
              <div className="cart-quantity">3</div>
              <div className="cart-text">Cart</div>
            </a>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
